# Generated by Django 4.0.4 on 2022-06-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_de_criacao',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_de_publicacao',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='texto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
    ]
